# Add core reviewers to Pull Request.
name: 1 Stage of Approval PR process
on:
  pull_request: 
    types: [opened, reopened]

jobs:
  onOpenedPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Request core reviewers.
        uses: necojackarc/auto-request-review@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/core-reviewers.yml
